services:
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: arteluce-nginx
    volumes:
      - ./nginx-m.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - default
    restart: unless-stopped

  backend:
    image: ghcr.io/amylamino/arteluce-backend:latest
    container_name: arteluce-backend
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
    restart: unless-stopped
    pull_policy: always

  frontend:
    image: ghcr.io/amylamino/arteluce-frontend:latest
    container_name: arteluce-frontend
    #ports:
    #  - "3000:3000"
    environment:
      - NODE_ENV=production
      # Do not override NEXT_PUBLIC_API_* here so frontend built image
      # will use the internal backend service URL baked into the image
      # (it defaults to http://backend:8000/api in the Dockerfile)
    depends_on:
      - backend
    restart: unless-stopped
    pull_policy: always

networks:
  default:
    name: arteluce_net
